### ISSUE TITLE
Restoring backups from Moodle 1.9

### ISSUE THREAD

**Issue by temin** [netspotau/moodle-mod_lightboxgallery#81]
I have 193 course backups from Moodle 1.9 with 772 Lightbox Galleries in them. I would like to restore the courses on the latest Moodle.
If I try to restore the courses on any Moodle 2.x or 3.x the galleries are not restored at all.
I can restore the courses on Moodle 1.9 and view the images in galleries. After I upgrade the Moodle to 2.x the galleries are still there, but images are not visible. The files/images from galleries are accessible through 'Legacy files', but they are not displayed in galleries.
I'm using latest Moodle versions (from Git) and latest plugin versions (from https://moodle.org/plugins/mod_lightboxgallery).

**Comment by aolley** [comment]
Hi,

lightboxgallery does not currently support restoring back ups from Moodle 1.9.

One work-around is to restore them into a 1.9 Moodle and upgrading that Moodle in place to newer version (along with the newer lightboxgallery plugin to go with it) and then export the backups from that.

Otherwise, someone will need to develop M1.9 restore code for lightboxgallery.

**Comment by temin** [comment]
There is some mismatch between the latest code for Moodle 1.9 and Lightbox Gallery plugin, that are available on-line.
I finally got my hands on the code from the existing installation, and the upgrade went smoothly up till Moodle 3.3.
Thank you for your help.
